// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var app, auth, express, home, http, passport, path, setupRoutes;
  express = require('express.io');
  setupRoutes = require('./routes');
  http = require('http');
  path = require('path');
  home = require('./controllers/home');
  app = express();
  auth = require('./auth');
  passport = require('passport');
  app.set('port', process.env.PORT || 3e3);
  app.set('views', path.join(__dirname, 'views'));
  app.set('view engine', 'jade');
  app.use(express.favicon());
  app.use(express.json());
  app.use(express.urlencoded());
  app.use(express.methodOverride());
  app.use(express.cookieParser());
  app.use(express.bodyParser());
  app.use(express.session({ secret: 'somesesi1onSikrit09#123' }));
  app.use(passport.initialize());
  app.use(passport.session());
  app.use(app.router);
  app.use(express['static'](path.join(__dirname, 'public')));
  auth.configure();
  if ('development' === app.get('env'))
    app.use(express.errorHandler());
  app.http().io();
  setupRoutes(app);
  app.listen(app.get('port'), function () {
    return console.log('HTTP server listening on port ' + app.get('port'));
  });
  app.use(home);
}.call(this);

//# sourceMappingURL=app.js.map
