// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var socketDAO, userDAO;
  userDAO = require('../services/userDAO');
  socketDAO = require('../services/socketDAO');
  module.exports = function (req, res) {
    return userDAO.find(req.session.passport.user).then(function (user) {
      socketDAO.store(user.username, req.io);
      return req.io.emit('user', user);
    }).done();
  };
}.call(this);

//# sourceMappingURL=socketCapture.js.map
