// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var handle, socketDAO;
  socketDAO = require('./socketDAO');
  handle = function (username, action, data) {
    return socketDAO.get(username).forEach(function (io) {
      return io.emit('upd', {
        action: action,
        data: data
      });
    });
  };
  module.exports = { handle: handle };
}.call(this);

//# sourceMappingURL=sync.js.map
